### ISSUE TITLE
login return undefined url

### ISSUE THREAD

**Issue by gabrielchavezme** [kvithana/musictaste.space#68]
I am trying to do an integration in my repository locale.

I have managed to configure the .env file by following the configuration of the Firebase.tsx file a bit.

The frontend looks like it should but there is a problem clicking the "Sign In" button, it opens the popup but returns "http: // localhost: 3000 / undefined"

I suspect that maybe it could be a bad configuration of the .env file, could you guide me a bit?

**Comment by kvithana** [comment]
This repo currently cannot be developed on without the relevant firebase functions emulation and access to the development cache API. Due to privacy reasons and protecting against attacks, the backend repo is currently private. This might change in the future!
